README.md

Fix https://github.com/gmacario/gmacario.github.io/issues/7

Extend Copyright to 2015

---

_posts/2015-03-22-inspecting-yun-linux-configuration.md

Fix https://github.com/gmacario/gmacario.github.io/issues/19

New Blog post: Inspecting the Linux configuration on my Yun

---

_drafts/upgrading-openwrt-on-my-yun.md

_drafts: Add upgrading-openwrt-on-my-yun.md

---

_config.yml

Fix https://github.com/gmacario/gmacario.github.io/issues/28

Enable GitHub Flavored Markdown

---

.gitignore

Fix https://github.com/gmacario/gmacario.github.io/issues/34

Add to .gitignore: Gemfile.lock

---

_posts/2015-04-11-notes-from-cyanogenmod-workshop-at-it-droidcon-2015.md

Fix https://github.com/gmacario/gmacario.github.io/issues/36

Fix minor formatting issues

---

_drafts/using-jekyll-with-pages.md
_posts/2015-04-15-using-jekyll-with-pages.md

Post article: Using Jekyll with Google Pages

---

_drafts/00-template-blog-post.md

First shot at blog post template

---

_drafts/00-template-blog-post.md

See also: http://www.tablesgenerator.com/markdown_tables

Add sample table

---

bio/gmacario-cv-en.html

Refresh contents

---

README.md

README: Add CircleCI status badge

---

.circleci/config.yml

Switch to CircleCI 2.0

---

.github/workflows/check-links.yml

Based on https://github.com/per1234/arduino-ci-script/blob/master/.github/workflows/check-links.yml

[feature] Check links in .md files

---

LICENSE
_includes/footer.js
_includes/header.js
_layouts/default.js
_layouts/post.js
api/index.js
next.config.js
pages/_app.js
pages/index.js
pages/posts/[slug].js
pages/posts/index.js
postcss.config.js
tailwind.config.js

Hi!
This could solve issue #38

Add a license file

---

.github/workflows/integrate.yml
.npmrc
package.json

Enforce the node and npm versions

Migrate to next js

---

README.md

Minor changes to the README.md in order to re-deploy the static website to gh-pages.
See #96

Add section: "Running tests on the static build"

---

.github/workflows/build.yml
.github/workflows/release.yml

Split the integrate workflow into:
- build.yml
- Is triggered by a push or pull-request
- Runs on every branch except main (or master) when pushing
- Builds the project and exports static files
- deploy.yml
- Is triggered by a push
- Runs only on main (or master) branch
- Builds, exports and deploys the project on branch gh-pages
see #104

Update git workflow

---

_posts/2022-01-10-arneis-dev-cw01.md

Signed-off-by: Macario Gianpaolo <gmacario@gmail.com>

[Feat] Add post: ARNEIS dev-cw01 status report

---

_posts/2022-01-31-arneis-dev-cw04.md

[Feat] New post: ARNEIS dev-cw04 status report

---

_posts/2022-01-31-arneis-dev-cw04.md

Signed-off-by: Macario Gianpaolo <gmacario@gmail.com>

[Fix] 2022-01-31-arneis-dev-cw04: Quick fixes and improvements

---

.github/linters/.textlintrc
_posts/2022-02-07-arneis-dev-cw05.md

Closes https://github.com/B-AROL-O/ARNEIS/issues/15

[Feat] arneis dev-cw05

---

_posts/2022-02-07-arneis-dev-cw05.md
_posts/2022-02-14-arneis-dev-cw06.md

Should fix https://github.com/B-AROL-O/ARNEIS/issues/16
Signed-off-by: Macario Gianpaolo <gmacario@gmail.com>

[Feat] New post: 2022-02-14-arneis-dev-cw06

---

_posts/2022-03-07-arneis-dev-cw09.md

Closes https://github.com/B-AROL-O/ARNEIS/issues/19

[Feat] Add ARNEIS project status report dev-cw09

---

.github/linters/.textlintrc
_posts/2022-03-14-arneis-dev-cw10.md

Closes https://github.com/B-AROL-O/ARNEIS/issues/20

[Feat] Add ARNEIS Project Report for cw10-2022

---

_posts/2022-03-14-arneis-dev-cw10.md

Text copied from https://github.com/B-AROL-O/ARNEIS/tree/main/mocs/project
Signed-off-by: Macario Gianpaolo <gmacario@gmail.com>

arneis-dev-cw10: Expand text for first highlight

---

_posts/2022-03-21-arneis-dev-cw11.md

Closes https://github.com/B-AROL-O/ARNEIS/issues/21

[Feat] New blog post: 2022-03-21-arneis-dev-cw11

---

README.md

[Feat] Update section: Copyright and license
